# Generated by Django 5.1.7 on 2025-03-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmap", "0002_remove_profile_first_name_remove_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="grade",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=40.4433, max_digits=9),
        ),
        migrations.AlterField(
            model_name="profile",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default=-79.9436, max_digits=9),
        ),
    ]
