# Generated by Django 5.1.7 on 2025-03-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmap', '0003_alter_profile_grade_alter_profile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content_type',
            field=models.CharField(default='jpeg', max_length=50),
        ),
    ]
